<?php

namespace Database\Seeders;

use App\Models\HariModul;
use App\Models\Kuis;
use App\Models\Modul;
use App\Models\ProgramPembelajaran;
use App\Services\KuisDokkaiService;
use Illuminate\Database\Seeder;

class DokkaiSeeder extends Seeder
{
    public function __construct(
        private readonly KuisDokkaiService $dokkaiService
    ) {}

    public function run(): void
    {
        // Cari module day target (utamakan program kelas demo atau hari modul pertama)
        $day = HariModul::query()->first();
        $module = $day ? $day->module : Modul::query()->first();

        if (! $module) {
            // Jika belum ada modul sama sekali di DB, buat placeholder agar seeder mandiri
            $program = ProgramPembelajaran::query()->first();
            $module = Modul::create([
                'program_pembelajaran_id' => $program?->id,
                'title' => 'Modul 1: Pemahaman Membaca Dokkai',
                'week_number' => 1,
                'status' => 'published',
            ]);
        }

        if (! $day) {
            $day = HariModul::create([
                'module_id' => $module->id,
                'day_number' => 1,
                'title' => 'Hari 1: Membaca Wacana',
                'status' => 'published',
            ]);
        }

        $quiz = Kuis::updateOrCreate(
            [
                'module_id' => $module->id,
                'module_day_id' => $day->id,
                'type' => 'dokkai',
            ],
            [
                'status' => 'published',
                'passing_score' => 70,
                'time_limit' => 300,
                'available_at' => now(),
            ]
        );

        $payload = [
            'passage' => [
                'title' => '日本の四季と自然観',
                'sub_title' => 'Four Seasons & Environmental Consciousness: Tradisi pergantian musim dalam kebudayaan Jepang.',
                'theme_category' => 'Budaya & Tradisi',
                'jlpt_level' => 'N3',
                'estimated_reading_time' => 4,
                'xp_reward' => 80,
                'audio_url' => null,
            ],
            'paragraphs' => [
                [
                    'paragraph_number' => 1,
                    'label' => 'Paragraf 1 · Latar Belakang Iklim & Pergantian Musim',
                    'content_raw' => '日本には、春、夏、秋、冬という明確な四季が存在します。移り変わりの中で、人々は昔から自然の美しさを感じ取り、文学や絵画に表現してきました。風や雨の音にも名前をつけ、日々の暮らしに豊かさを見出しています。',
                ],
                [
                    'paragraph_number' => 2,
                    'label' => 'Paragraf 2 · Estetika Sastra & Filosofi Mono no Aware',
                    'content_raw' => '特に花見や紅葉狩りのように、季節の植物を愛でる行事は、単に景色を楽しむだけでなく、散りゆく花の命に「もののあわれ」という日本特有の感情を重ねる機会でもありました。自然とともに生きる姿勢が、日本人の価値観の基盤を作っています。',
                ],
                [
                    'paragraph_number' => 3,
                    'label' => 'Paragraf 3 · Kesimpulan & Refleksi Modernitas',
                    'content_raw' => '現代の都市生活においても、旬の食材を食べたり季節の飾り物を置いたりと、自然とのつながりを保とうとする工夫が続いています。このように、自然への敬意と共存の心は、形を変えながらも今なお受け継がれているのです。',
                ],
            ],
            'vocabularies' => [
                [
                    'word' => '日本',
                    'furigana' => 'にほん',
                    'romaji' => 'nihon',
                    'meaning' => 'Negara Jepang.',
                    'pitch_accent' => '[2] 尾高型 (Odaka)',
                    'example_sentence' => '日本には、春、夏、秋、冬という明確な四季が存在します。',
                    'example_translation' => 'Di Jepang, terdapat empat musim yang jelas: semi, panas, gugur, dan dingin.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '四季',
                    'furigana' => 'しき',
                    'romaji' => 'shiki',
                    'meaning' => 'Empat musim (musim semi, panas, gugur, dingin).',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '四季の移り変わりの中で、美意識が育まれました。',
                    'example_translation' => 'Di tengah pergantian empat musim, kepekaan estetika tumbuh.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '春',
                    'furigana' => 'はる',
                    'romaji' => 'haru',
                    'meaning' => 'Musim semi.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '春になると桜の花が咲きます。',
                    'example_translation' => 'Saat musim semi tiba, bunga sakura bermekaran.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '夏',
                    'furigana' => 'なつ',
                    'romaji' => 'natsu',
                    'meaning' => 'Musim panas.',
                    'pitch_accent' => '[2] 尾高型 (Odaka)',
                    'example_sentence' => '日本の夏は湿度が高く暑いです。',
                    'example_translation' => 'Musim panas di Jepang lembap dan panas.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '秋',
                    'furigana' => 'あき',
                    'romaji' => 'aki',
                    'meaning' => 'Musim gugur.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '秋は読書や行楽に適した季節です。',
                    'example_translation' => 'Musim gugur adalah musim yang cocok untuk membaca dan bertamasya.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '冬',
                    'furigana' => 'ふゆ',
                    'romaji' => 'fuyu',
                    'meaning' => 'Musim dingin.',
                    'pitch_accent' => '[2] 尾高型 (Odaka)',
                    'example_sentence' => '冬には雪が降り積もります。',
                    'example_translation' => 'Di musim dingin salju turun dan menumpuk.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '明確',
                    'furigana' => 'めいかく',
                    'romaji' => 'meikaku',
                    'meaning' => 'Jelas, terang, definitif.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '明確な理由を説明してください。',
                    'example_translation' => 'Tolong jelaskan alasan yang jelas.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Adjektiva-Na',
                ],
                [
                    'word' => '存在',
                    'furigana' => 'そんざい',
                    'romaji' => 'sonzai',
                    'meaning' => 'Keberadaan, eksistensi.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '目に見えないが確かに存在する。',
                    'example_translation' => 'Tidak terlihat oleh mata namun benar-benar eksis.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina / Verba Suru',
                ],
                [
                    'word' => '移り変わり',
                    'furigana' => 'うつりかわり',
                    'romaji' => 'utsurikawari',
                    'meaning' => 'Pergantian, transisi, perubahan siklus.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '季節の移り変わりは早いです。',
                    'example_translation' => 'Pergantian musim berlangsung sangat cepat.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '自然',
                    'furigana' => 'しぜん',
                    'romaji' => 'shizen',
                    'meaning' => 'Alam semesta, alamiah.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '自然の恵みに深く感謝する。',
                    'example_translation' => 'Mensyukuri anugerah alam yang melimpah.',
                    'jlpt_level' => 'N4',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '美しさ',
                    'furigana' => 'うつくしさ',
                    'romaji' => 'utsukushisa',
                    'meaning' => 'Keindahan, pesona, estetika.',
                    'pitch_accent' => '[3] 中高型 (Nakadaka)',
                    'example_sentence' => '日本の景色の美しさに感動しました。',
                    'example_translation' => 'Saya terharu oleh keindahan pemandangan alam Jepang.',
                    'jlpt_level' => 'N4',
                    'part_of_speech' => 'Nomina (Turunan Adjektiva-I)',
                ],
                [
                    'word' => '感じ取り',
                    'furigana' => 'かんじとり',
                    'romaji' => 'kanjitori',
                    'meaning' => 'Merasakan secara mendalam, menangkap kesan batin.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '作者の繊細な意図を感じ取る。',
                    'example_translation' => 'Merasakan dan menangkap maksud halus dari sang penulis.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Verba (Bentuk Masu)',
                ],
                [
                    'word' => '文学',
                    'furigana' => 'ぶんがく',
                    'romaji' => 'bungaku',
                    'meaning' => 'Sastra, karya kesusastraan.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '日本文学を大学で専攻しています。',
                    'example_translation' => 'Saya mengambil jurusan sastra Jepang di universitas.',
                    'jlpt_level' => 'N4',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '絵画',
                    'furigana' => 'かいが',
                    'romaji' => 'kaiga',
                    'meaning' => 'Seni lukis, gambar lukisan.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '美術館で貴重な絵画を鑑賞した。',
                    'example_translation' => 'Menikmati lukisan berharga di museum seni.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '表現',
                    'furigana' => 'ひょうげん',
                    'romaji' => 'hyougen',
                    'meaning' => 'Ekspresi, penggambaran, ungkapan.',
                    'pitch_accent' => '[3] 中高型 (Nakadaka)',
                    'example_sentence' => '言葉で気持ちを表現するのは難しい。',
                    'example_translation' => 'Mengungkapkan perasaan lewat kata-kata itu sulit.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina / Verba Suru',
                ],
                [
                    'word' => '風',
                    'furigana' => 'かぜ',
                    'romaji' => 'kaze',
                    'meaning' => 'Angin, hembusan.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '心地よい春の風が吹いている。',
                    'example_translation' => 'Angin musim semi yang sejuk sedang berhembus.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '雨',
                    'furigana' => 'あめ',
                    'romaji' => 'ame',
                    'meaning' => 'Hujan.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '静かに雨が降り続いている。',
                    'example_translation' => 'Hujan turun tanpa henti dengan tenang.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '音',
                    'furigana' => 'おと',
                    'romaji' => 'oto',
                    'meaning' => 'Bunyi, suara benda.',
                    'pitch_accent' => '[2] 尾高型 (Odaka)',
                    'example_sentence' => '雨の音が屋根に心地よく響く。',
                    'example_translation' => 'Suara hujan terdengar merdu di atas atap.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '名前',
                    'furigana' => 'なまえ',
                    'romaji' => 'namae',
                    'meaning' => 'Nama, sebutan.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '日本語には雨に数十もの名前がある。',
                    'example_translation' => 'Dalam bahasa Jepang ada puluhan sebutan nama untuk hujan.',
                    'jlpt_level' => 'N5',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '日々',
                    'furigana' => 'ひび',
                    'romaji' => 'hibi',
                    'meaning' => 'Hari demi hari, keseharian.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '穏やかな日々を過ごしています。',
                    'example_translation' => 'Menghabiskan hari-hari yang tenteram.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '暮らし',
                    'furigana' => 'くらし',
                    'romaji' => 'kurashi',
                    'meaning' => 'Kehidupan sehari-hari, cara hidup.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '自然に近い暮らしに憧れます。',
                    'example_translation' => 'Saya mendambakan kehidupan yang dekat dengan alam.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '豊かさ',
                    'furigana' => 'ゆたかさ',
                    'romaji' => 'yutakasa',
                    'meaning' => 'Kekayaan batin, kelimpahan rasa.',
                    'pitch_accent' => '[3] 中高型 (Nakadaka)',
                    'example_sentence' => '心の豊かさを大切にしたい。',
                    'example_translation' => 'Saya ingin menjunjung tinggi kekayaan batin.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina (Turunan Adjektiva-Na)',
                ],
                [
                    'word' => '見出しています',
                    'furigana' => 'みいだしています',
                    'romaji' => 'miidashiteimasu',
                    'meaning' => 'Menemukan makna, menggali nilai.',
                    'pitch_accent' => '[5] 中高型 (Nakadaka)',
                    'example_sentence' => '日々の暮らしの中に喜びを見出す。',
                    'example_translation' => 'Menemukan kebahagiaan di dalam kehidupan sehari-hari.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Verba (Bentuk Masu)',
                ],
                [
                    'word' => '花見',
                    'furigana' => 'はなみ',
                    'romaji' => 'hanami',
                    'meaning' => 'Piknik tradisi melihat bunga sakura mekar di musim semi.',
                    'pitch_accent' => '[3] 中高型 (Nakadaka)',
                    'example_sentence' => '家族で公園へ花見に出かけました。',
                    'example_translation' => 'Pergi hanami ke taman bersama keluarga.',
                    'jlpt_level' => 'N4',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '紅葉狩り',
                    'furigana' => 'もみじがり',
                    'romaji' => 'momijigari',
                    'meaning' => 'Wisata menikmati keindahan daun musim gugur yang memerah.',
                    'pitch_accent' => '[4] 尾高型 (Odaka)',
                    'example_sentence' => '秋の京都へ紅葉狩りに行きました。',
                    'example_translation' => 'Pergi bertamasya melihat daun gugur ke Kyoto di musim gugur.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '愛でる',
                    'furigana' => 'めでる',
                    'romaji' => 'mederu',
                    'meaning' => 'Mencintai, mengagumi keindahan dengan kasih sayang.',
                    'pitch_accent' => '[2] 中高型 (Nakadaka)',
                    'example_sentence' => '満月を静かに愛でる風習がある。',
                    'example_translation' => 'Ada tradisi mengagumi bulan purnama dengan tenang.',
                    'jlpt_level' => 'N1',
                    'part_of_speech' => 'Verba Transitif',
                ],
                [
                    'word' => '行事',
                    'furigana' => 'ぎょうじ',
                    'romaji' => 'gyouji',
                    'meaning' => 'Acara tradisi, kegiatan seremonial tahunan.',
                    'pitch_accent' => '[1] 頭高型 (Atamadaka)',
                    'example_sentence' => '季節ごとの伝統行事に参加する。',
                    'example_translation' => 'Mengikuti kegiatan acara tradisional di setiap musim.',
                    'jlpt_level' => 'N3',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => 'もののあわれ',
                    'furigana' => 'もののあわれ',
                    'romaji' => 'mono no aware',
                    'meaning' => 'Konsep estetika Jepang tentang keharuan mendalam terhadap kefanaan alam.',
                    'pitch_accent' => '[5] 中高型 (Nakadaka)',
                    'example_sentence' => '散る桜にもののあわれを感じる。',
                    'example_translation' => 'Merasakan "mono no aware" pada bunga sakura yang berguguran.',
                    'jlpt_level' => 'N1',
                    'part_of_speech' => 'Frasa Estetika Filosofis',
                ],
                [
                    'word' => '基盤',
                    'furigana' => 'きばん',
                    'romaji' => 'kiban',
                    'meaning' => 'Fondasi, landasan dasar, basis pokok.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '文化の基盤を理解することが不可欠です。',
                    'example_translation' => 'Memahami landasan budaya adalah hal yang mutlak.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '旬',
                    'furigana' => 'しゅん',
                    'romaji' => 'shun',
                    'meaning' => 'Musim panen terbaik untuk bahan makanan tertentu.',
                    'pitch_accent' => '[0] 平板型 (Heiban)',
                    'example_sentence' => '旬の魚は脂がのっておいしい。',
                    'example_translation' => 'Ikan yang sedang musim rasanya sangat lezat berlemak.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Nomina (Kata Benda)',
                ],
                [
                    'word' => '受け継がれる',
                    'furigana' => 'うけつがれる',
                    'romaji' => 'uketsugareru',
                    'meaning' => 'Diwariskan, diteruskan dari generasi ke generasi.',
                    'pitch_accent' => '[5] 中高型 (Nakadaka)',
                    'example_sentence' => '形を変えながらも今なお受け継がれているのです。',
                    'example_translation' => 'Meski berganti wujud, tradisi itu tetap diwariskan hingga kini.',
                    'jlpt_level' => 'N2',
                    'part_of_speech' => 'Verba Pasif',
                ],
            ],
            'questions' => [
                [
                    'question_number' => 1,
                    'question_text' => '筆者によると、昔の日本人は四季の移り変わりに対してどのように接してきましたか。',
                    'question_translation' => 'Menurut penulis, bagaimanakah orang Jepang zaman dahulu menyikapi pergantian empat musim?',
                    'evidence_paragraph_number' => 1,
                    'evidence_quote' => '人々は昔から自然の美しさを感じ取り、文学や絵画に表現してきました。',
                    'explanation_correct' => 'Paragraf pertama menyatakan secara eksplisit bahwa orang Jepang zaman dahulu merasakan keindahan alam serta mengekspresikannya ke dalam karya sastra dan lukisan.',
                    'explanation_distractors' => [
                        'A' => 'Teks tidak menyebutkan bahwa orang zaman dahulu melarikan diri ke kota.',
                        'C' => 'Konsep mendominasi alam bertolak belakang dengan filosofi harmoni dalam teks.',
                        'D' => 'Orang Jepang justru melestarikan perayaan musiman, bukan menghapusnya.',
                    ],
                    'options' => [
                        ['id' => 1, 'option_label' => 'A', 'option_text' => '自然の厳しさを避けるために、都市へ移住していった。', 'option_translation' => 'Pindah ke perkotaan demi menghindari kerasnya alam.', 'is_correct' => false],
                        ['id' => 2, 'option_label' => 'B', 'option_text' => '美しさを感じ取り、文学や絵画などの芸術に表現してきた。', 'option_translation' => 'Merasakan keindahannya dan mengekspresikannya ke seni sastra maupun lukisan.', 'is_correct' => true],
                        ['id' => 3, 'option_label' => 'C', 'option_text' => '自然を支配し、農業の収穫量を増やすことに専念した。', 'option_translation' => 'Menguasai alam dan berfokus meningkatkan hasil panen.', 'is_correct' => false],
                        ['id' => 4, 'option_label' => 'D', 'option_text' => '季節の行事を廃止し、個人の生活を優先するようになった。', 'option_translation' => 'Menghapus perayaan musiman dan mendahulukan kehidupan pribadi.', 'is_correct' => false],
                    ],
                    'order' => 1,
                ],
                [
                    'question_number' => 2,
                    'question_text' => '本文中の「もののあわれ」という感情の説明として、最も適切なものはどれですか。',
                    'question_translation' => 'Manakah penjelasan yang paling tepat mengenai perasaan "Mono no Aware" pada teks bacaan?',
                    'evidence_paragraph_number' => 2,
                    'evidence_quote' => '散りゆく花の命に「もののあわれ」という日本特有の感情を重ねる機会でもありました。',
                    'explanation_correct' => 'Paragraf kedua menjelaskan bahwa "Mono no aware" tercermin ketika merenungkan siklus kehidupan bunga yang gugur, menyadari ketidakkekalan makhluk hidup di alam semesta.',
                    'explanation_distractors' => [
                        'A' => 'Mono no aware bukan keputusasaan, melainkan apresiasi keindahan dalam kefanaan.',
                        'B' => 'Teks menekankan harmoni dengan alam, bukan kemarahan.',
                        'D' => 'Pilihan D adalah fenomena modernitas yang terdistorsi, bukan makna filosofi ini.',
                    ],
                    'options' => [
                        ['id' => 1, 'option_label' => 'A', 'option_text' => 'いつまでも変わらない永遠の命を願う悲観的な気持ち。', 'option_translation' => 'Perasaan pesimis yang menginginkan kehidupan abadi tak berubah.', 'is_correct' => false],
                        ['id' => 2, 'option_label' => 'B', 'option_text' => '自然を思い通りにコントロールできないことへの怒り。', 'option_translation' => 'Kemarahan akibat tidak bisa mengendalikan alam sesuai kehendak.', 'is_correct' => false],
                        ['id' => 3, 'option_label' => 'C', 'option_text' => '散りゆく花の命のように、はかなさや美しさに心を動かされる感情。', 'option_translation' => 'Perasaan yang tersentuh oleh kefanaan dan keindahan seperti bunga yang gugur.', 'is_correct' => true],
                        ['id' => 4, 'option_label' => 'D', 'option_text' => '現代社会の便利さに満足し、自然を忘れてしまう心理。', 'option_translation' => 'Psikologi melupakan alam karena merasa puas dengan kenyamanan modern.', 'is_correct' => false],
                    ],
                    'order' => 2,
                ],
                [
                    'question_number' => 3,
                    'question_text' => '現代の日本において、自然への敬意はどのように受け継がれていますか。',
                    'question_translation' => 'Di Jepang masa kini, bagaimanakah penghormatan terhadap alam diwariskan dalam kehidupan modern?',
                    'evidence_paragraph_number' => 3,
                    'evidence_quote' => '旬の食材を食べたり季節の飾り物を置いたりと、自然とのつながりを保とうとする工夫が続いています。',
                    'explanation_correct' => 'Paragraf ketiga menjelaskan bahwa masyarakat kota modern menjaga keharmonisan dengan mengonsumsi makanan bermusim (shun) dan menata dekorasi musiman.',
                    'explanation_distractors' => [
                        'B' => 'Teks tidak menyebutkan keharusan warga membeli hutan.',
                        'C' => 'Tradisi tetap hidup dalam keseharian, tidak terbatas di museum.',
                        'D' => 'Teks menyebutkan upaya terhubung dengan musim, bukan mengaburkannya.',
                    ],
                    'options' => [
                        ['id' => 1, 'option_label' => 'A', 'option_text' => '旬の食材を食べたり、季節の飾り物を飾る工夫を通じて続いている。', 'option_translation' => 'Berlanjut lewat inovasi menyantap makanan bermusim dan memasang dekorasi musiman.', 'is_correct' => true],
                        ['id' => 2, 'option_label' => 'B', 'option_text' => 'すべての都市住民が山林を購入して自然保護活動を行うことで。', 'option_translation' => 'Dengan setiap penduduk kota membeli hutan untuk konservasi alam.', 'is_correct' => false],
                        ['id' => 3, 'option_label' => 'C', 'option_text' => '伝統行事が完全に忘れ去られ、博物館の展示のみで見られる。', 'option_translation' => 'Tradisi telah sepenuhnya dilupakan dan hanya tersisa di museum.', 'is_correct' => false],
                        ['id' => 4, 'option_label' => 'D', 'option_text' => '四季の区分をなくし、一年中同じ気温の部屋で過ごすことで。', 'option_translation' => 'Dengan menghilangkan batas musim dan tinggal di ruangan ber-AC konstan.', 'is_correct' => false],
                    ],
                    'order' => 3,
                ],
            ],
        ];

        $this->dokkaiService->sync($quiz, $payload);
    }
}
