import React from 'react';
import { Head, Link } from '@inertiajs/react';
import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import AccessTimeRoundedIcon from '@mui/icons-material/AccessTimeRounded';
import QuizOutlinedIcon from '@mui/icons-material/QuizOutlined';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { PrototypeNotice } from '@/Components/Features/AdminExam/AdminExamUI';

export default function Preview({ exam }) {
    return <AuthenticatedLayout><Head title={`Preview ${exam.title}`} /><div className="min-h-screen bg-[#eef7f1] px-4 py-7 dark:bg-[#0b1121] sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl">
        <header className="flex flex-col gap-4 border-b border-[#cfddd4] pb-5 dark:border-gray-800 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><Link href="/admin/exams" className="grid h-10 w-10 place-items-center rounded-md border border-[#c8d8ce] bg-white text-gray-600 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300"><ArrowBackRoundedIcon fontSize="small" /></Link><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-black text-gray-950 dark:text-white">Preview sebagai peserta</h1><PrototypeNotice /></div><p className="mt-1 text-sm text-gray-500">Tombol mulai dinonaktifkan pada mode admin.</p></div></div><Link href={`/admin/exams/${exam.slug}/edit`} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-brand-600 px-4 text-sm font-black text-white"><EditOutlinedIcon fontSize="small" /> Kembali ke editor</Link></header>
        <main className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_310px]"><section className="border border-[#d4e0d8] bg-white p-6 dark:border-gray-800 dark:bg-gray-900 sm:p-8"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-brand-50 px-2.5 py-1 text-xs font-black text-brand-700 dark:bg-brand-950/40 dark:text-brand-300">{exam.level}</span><span className="text-xs font-black text-gray-500">{exam.type === 'simulation' ? 'Simulasi JLPT' : 'Latihan ujian'}</span></div><h2 className="mt-5 text-3xl font-black leading-tight text-gray-950 dark:text-white">{exam.title}</h2><p className="mt-3 max-w-2xl text-sm font-medium leading-7 text-gray-600 dark:text-gray-300">{exam.description}</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="flex items-center gap-3 border border-gray-200 p-4 dark:border-gray-700"><AccessTimeRoundedIcon className="text-sky-500" /><div><p className="text-xs font-bold text-gray-500">Durasi</p><p className="font-black">{exam.duration_minutes} menit</p></div></div><div className="flex items-center gap-3 border border-gray-200 p-4 dark:border-gray-700"><QuizOutlinedIcon className="text-amber-500" /><div><p className="text-xs font-bold text-gray-500">Jumlah soal</p><p className="font-black">{exam.question_count} soal</p></div></div></div><button type="button" disabled className="mt-7 h-12 w-full rounded-md bg-brand-600 text-sm font-black text-white opacity-55">Mulai ujian</button></section>
            <aside className="border border-[#d4e0d8] bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h3 className="font-black text-gray-950 dark:text-white">Bagian ujian</h3><ol className="mt-4 space-y-4">{exam.sections.map((section, index) => <li key={section.key} className="border-b border-gray-100 pb-4 last:border-0 last:pb-0 dark:border-gray-800"><p className="text-xs font-black text-brand-600">BAGIAN {index + 1}</p><p className="mt-1 text-sm font-black text-gray-900 dark:text-white">{section.short_label}</p><p className="mt-1 text-xs font-semibold text-gray-500">{section.question_count} soal · {section.duration_minutes} menit</p></li>)}</ol></aside></main>
    </div></div></AuthenticatedLayout>;
}
